name = "still-alive-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 这是一个定时触发器，设置每10分钟检查一次
# cron语法: "分钟 小时 天 月 星期"
# "*/10 * * * *" 代表每10分钟一次
[triggers]
crons = ["*/10 * * * *"]

# 数据库配置 (Key-Value Storage)
# 我们稍后需要运行命令生成 ID 并填入这里
[[kv_namespaces]]
binding = "STATUS_STORE"
id = "8d67a56f333b46a0a36f2be5f1cadf8f"
